name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: github-docs-to-wiki
       uses: cmbrose/github-docs-to-wiki@v0.24
       with:
          rootDocsFolder: "docs/"
          convertRootReadmeToHomePage: "true"
          useHeaderForWikiName: "true"
          githubToken: ${{ secrets.githubToken }}